---
# Part 1: Install Kubernetes on all nodes (master + workers)
- name: Install Kubernetes Cluster using kubeadm
  hosts: kube_cluster
  become: yes
  vars:
    kubernetes_version: "1.30.5"   # آخر إصدار مستقر ديسمبر 2025
  tasks:
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Disable swap permanently
      lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    - name: Load kernel modules
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf

    - name: Load modules now
      shell: modprobe overlay && modprobe br_netfilter

    - name: Set required sysctl params
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf
      notify: reload sysctl

    - name: Install common packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Kubernetes apt key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        state: present
        filename: kubernetes

    - name: Install containerd
      apt:
        name: containerd.io
        state: present

    - name: Configure containerd for Kubernetes
      copy:
        content: |
          version = 2
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
        dest: /etc/containerd/config.toml
      notify: restart containerd

    - name: Install kubelet, kubeadm, kubectl
      apt:
        name:
          - kubelet={{ kubernetes_version }}-1.00
          - kubeadm={{ kubernetes_version }}-1.00
          - kubectl={{ kubernetes_version }}-1.00
        state: present
        update_cache: yes

  handlers:
    - name: reload sysctl
      command: sysctl --system
    - name: restart containerd
      service:
        name: containerd
        state: restarted


# Part 2: Initialize Master Node
- name: Initialize Kubernetes Master
  hosts: master
  become: yes
  vars:
    kubernetes_version: "1.30.5"
  tasks:
    - name: Check if cluster already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_admin_conf

    - name: Initialize the cluster (only once)
      command: >
        kubeadm init --pod-network-cidr=10.244.0.0/16
        --kubernetes-version={{ kubernetes_version }}
      when: not k8s_admin_conf.stat.exists

    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf to ubuntu user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Install Calico CNI (Flannel alternative - more stable)
      become: yes
      become_user: ubuntu
      kubernetes.core.k8s:
        src: https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/calico.yaml
        state: present
      when: not k8s_admin_conf.stat.exists


# Part 3: Join Worker Nodes
- name: Join Workers to Cluster
  hosts: workers
  become: yes
  tasks:
    - name: Get join command from master
      command: kubeadm token create --print-join-command
      delegate_to: ec2-master
      register: join_command
      changed_when: yes

    - name: Join the cluster
      command: "{{ join_command.stdout }}"
      when: join_command.stdout is defined